### ISSUE TITLE
Edge - Prevent bypassing Microsoft Defender SmartScreen prompts for sites

### ISSUE THREAD

**Issue by VM-Master** [0x6d69636b/windows_hardening#117]
Hi,

first thanks for this awesome tool!

Can you please check list "finding_list_msft_security_baseline_edge_98_machine.csv" about "Prevent bypassing Microsoft Defender SmartScreen prompts for sites"

I set this policy through Edge GPO but the HardeningKitty report does not recognized it.
HardeningKitty checks for "HKLM:\Software\Policies\Microsoft\MicrosoftEdge\PhishingFilter,PreventOverride".
This seems for be right for the old edge legacy browser not for edge chromium.

correct should be "HKLM:\Software\Policies\Microsoft\Edge\PreventSmartScreenPromptOverride".
See here --> https://www.thewindowsclub.com/prevent-users-from-bypassing-smartscreen-warning-in-edge

Thanks in advance

**Comment by 0x6d69636b** [comment]
You're right. Fixed in commit [738f3e3](https://github.com/0x6d69636b/windows_hardening/commit/738f3e3c5d4b7a516b4a63413bd9647a1c7f3ef0)

**Comment by VM-Master** [comment]
Thanks for fixing!

**Comment by VM-Master** [comment]
Solved!
