### ISSUE TITLE
please consider using Set-StrictMode

### ISSUE THREAD

**Issue by rafalfitt** [0x6d69636b/windows_hardening#124]
Set-StrictMode -Version Latest

more info: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/set-strictmode?view=powershell-7.2

**Comment by 0x6d69636b** [comment]
Could you provide more information: Should the Strict-Mode set in the HardeningKitty module? Or is this an appendix for the hardening list? If so, what is the security/hardening benefit? Is there a group policy to set Strict-Mode?

**Comment by rafalfitt** [comment]
it is a Powershell command, so it is for the HardeningKitty module.

**Comment by rafalfitt** [comment]
https://devblogs.microsoft.com/scripting/enforce-better-script-practices-by-using-set-strictmode/

**Comment by An78toi13ne06** [comment]
Set-Strictmode is irrelevant in a release as this should only be use during the coding process and disabled in the production version.
Set-Strictmode only help getting more explicit error messages when developing.

**Comment by 0x6d69636b** [comment]
Thanks @An78toi13ne06 for the clarification. I ran HardeningKitty with Set-Strictmode on without any errors and will use it for new versions.
