### ISSUE TITLE
Feat: Add finding category to report file

### ISSUE THREAD

**Issue by maxilampert** [0x6d69636b/windows_hardening#125]
When creating a report it would be great if the category of the finding could be added to the output csv to make it easier to find the type of the setting without having to check with the findings file e.g. Account Polices, Administrative templates etc. this would help especially for the bigger lists like CIS where multiple categories are used and also later with filtering the report for specific categories.

**Comment by 0x6d69636b** [comment]
Okay, that makes senses. I update the report function in commit https://github.com/0x6d69636b/windows_hardening/commit/d3b7e30f0deb4a5432807c5e161810041c81aa89
