### ISSUE TITLE
External drives are write protected even after restoring backup

### ISSUE THREAD

**Issue by d1nuc0m** [0x6d69636b/windows_hardening#140]
Hi guys, I'm having a strange problem, Windows 10 Home 22H2:

- Opened Powershell as administrator, imported HardeningKitty
- I made a backup with `Invoke-HardeningKitty -Mode Config -Backup -BackupFile "./myBackup.csv"`
- Applied a finding list with `Invoke-HardeningKitty -Mode HailMary -FileFindingList ".\lists\finding_list_msft_security_baseline_windows_10_22h2_machine.csv"`
- Can't create or delete files/folders on external drive. Checked users permissions in Explorer security tab, only Administrators are allowed with full access and modify. Users can only read/execute. When I try to allow users to modify, I get the error "_An error occurred while applying security information to (...) The storage medium is write protected_"
- Restored backup with `Invoke-HardeningKitty -Mode HailMary -FileFindingList "./myBackup.csv"`
- Rebooted and the error still occurs. Any idea?

Edit:

- The external drive results as owned by SYSTEM. Trying to change user permissions or owner always ends in "The storage medium is write protected" (in an elevated CMD tried both `takeown /f X:` and `icacls "X:\*" /grant myUser:F` with the same result)
- It is not hardware related, on my Linux machine I can read/write the disk without problems

**Comment by 0x6d69636b** [comment]
The culprit must be ID 10758 - _BitLocker Drive Encryption: Removable Data Drives: Deny write access to removable drives not protected by BitLocker_, Registry _HKLM:\System\CurrentControlSet\Policies\Microsoft\FVE_ -> _RDVDenyWriteAccess_. You can either delete this key or set the value to 0

**Comment by 0x6d69636b** [comment]
The backup probably didn't work because you didn't define a finding list when you invoked the backup mode, so the default list was used - which is a different list than you were using for HailMary

**Comment by d1nuc0m** [comment]
> The culprit must be ID 10758 - _BitLocker Drive Encryption: Removable Data Drives: Deny write access to removable drives not protected by BitLocker_, Registry _HKLM:\System\CurrentControlSet\Policies\Microsoft\FVE_ -> _RDVDenyWriteAccess_. You can either delete this key or set the value to 0

Ok, this fixed the problem



> The backup probably didn't work because you didn't define a finding list when you invoked the backup mode, so the default list was used - which is a different list than you were using for HailMary

So the correct backup command (in this case) would have been `Invoke-HardeningKitty -Mode Config -Backup -BackupFile "./myBackup.csv" -FileFindingList ".\lists\finding_list_msft_security_baseline_windows_10_22h2_machine.csv"`?

**Comment by 0x6d69636b** [comment]
Yep exactly :+1:

**Comment by d1nuc0m** [comment]
- [x] Problem solved 
- [x] Documentation MR merged 

Time to close the issue
