### ISSUE TITLE
Windows settings *more strict* than recommended result in "Failed" test result

### ISSUE THREAD

**Issue by shaunm001** [0x6d69636b/windows_hardening#146]
Example 1: Rule ID 1204 recommends blocking **Guests** group, but test result is "Failed" if we block Guests group **in addition to** other groups such as **Domain Admins**.

Example 2: Rule ID 1323 recommends "Prompt for credentials on the secure desktop", but test result is "Failed" when we use the more restrictive setting "Automatically deny elevation requests".

**Comment by 0x6d69636b** [comment]
I updated the operator for rule IDs 1204-1206 to _contains_ and for rule ID 1323 to lesser or equal

**Comment by 0x6d69636b** [comment]
This led to issue #151 but should be fixed now
