### ISSUE TITLE
SMBv1 Support identifies "DisabledWithPayloadRemoved" as severe?

### ISSUE THREAD

**Issue by yllekz** [0x6d69636b/windows_hardening#149]
Hello, I ran this script in audit mode and was perplexed to have the script identify a "severe" line item for when SMBv1 support is configured "DisabledWithPayloadRemoved" in a Server 2022 CIS L1 Benchmark image. Wouldn't this be more secure than the "Disabled" recommendation?

**Comment by 0x6d69636b** [comment]
Good point, I didn't know that there are other states for disabled. I changed the operator for this finding to 'contains'
