### ISSUE TITLE
Invocation failure in results check

### ISSUE THREAD

**Issue by MrZuerrer** [0x6d69636b/windows_hardening#151]
I downloaded the most current version of HardeningKitty today.
I invoked HardeningKitty with the following command:
"Invoke-HardeningKitty -Mode Audit -EmojiSupport -Report -Log -FileFindingList .\lists\finding_list_0x6d69636b_machine.csv -SkipMachineInformation"
I received the following error message 3 times in total.
- Before "[🙀] ID 1000, SMBv1 Support, Result=**Disabled**, Recommended=**Disabled**, Severity=High"
- Before "[😿] ID 2103, Disable PowerShell version 2, Result=Enabled, Recommended=Disabled, Severity=Medium"
- Before "[😿] ID 2104, Disable PowerShell version 2 (root), Result=Enabled, Recommended=Disabled, Severity=Medium"

Method invocation failed because [Microsoft.Dism.Commands.FeatureState] does not contain a method named 'Contains'.
At C:\Temp\COMPUTER\HardeningKitty\0.9.1\HardeningKitty.psm1:1459 char:38
+ ...  "contains" { If ($Result.Contains($Finding.RecommendedValue)) { $Res ...
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

I am happy to provide more information if required for debugging.
Thanks for a great tool and your support in keeping it sharp!
Peter

**Comment by 0x6d69636b** [comment]
Thanks! Should be fixed in the latest version :crossed_fingers:

**Comment by MrZuerrer** [comment]
I just re-ran the updated code. The error is gone. Thanks a lot for the quick fix!
