### ISSUE TITLE
Uninstallation Instructions

### ISSUE THREAD

**Issue by Astorias96** [0x6d69636b/windows_hardening#161]
Hello 0x6d69636b,

First things first, thank you for this nice repository.

I used your automatic script to install HardeningKitty. I was unable to remove the module using Remove-Module, I had to delete the files manually, but I am unsure if this is the best method in case of version upgrades. Can you please provide uninstall instructions ?

Thank you in advance for your feedback.

Kind regards,
Astorias96

**Comment by 0x6d69636b** [comment]
Hi Astorias96,

Thank you for your feedback! :heart_eyes_cat: 

Remove-Module removes a module in the current session, it does not uninstall the module itself. I would just add the latest version and remove the folder(s) of the old version(s).

Best, Mick

**Comment by Astorias96** [comment]
Hello Mick,

Thank you for your help. This allows me to prepare the correct update sequence for HardeningKitty. However, could you please confirm if Remove-Module and deleting the old files would 'uninstall' the module itself ? I was unable to uninstall it using Uninstall-Module cmdlet.

Thank you in advance for your feedback.
Best, Astorias96

**Comment by 0x6d69636b** [comment]
_Remove-Module_ alone will not uninstall an old version. _Uninstall-Module_ only works for modules installed with _Install-Module_. So you cannot use it for HardeningKitty. If you remove all files of an version, that version is "completely gone".

**Comment by Astorias96** [comment]
Many thanks for your replies & explanations !
Kind regards,
Astorias96
