### ISSUE TITLE
Question About the Use of SecEdit

### ISSUE THREAD

**Issue by lonkey** [0x6d69636b/windows_hardening#165]
Hello,

I am currently working on another automation project that also uses SecEdit to import local security policies. To give me a little idea of how this works, I have used the following [code section](https://github.com/0x6d69636b/windows_hardening/blob/443e7ab87bd43209181dddc59b5eab3998dbc016/HardeningKitty.psm1#L2002-L2072) from HardeningKitty as a reference:

```ps
$Area = "";

Switch ($Finding.Category) {
    "Account Policies" { $Area = "SECURITYPOLICY"; Break }
    "Security Options" { $Area = "SECURITYPOLICY"; Break }
}

$TempFileName = [System.IO.Path]::GetTempFileName()
$TempDbFileName = [System.IO.Path]::GetTempFileName()

&$BinarySecedit /export /cfg $TempFileName /areas $Area | Out-Null

$Data = Get-IniContent $TempFileName

Set-HashtableValueDeep -Table $Data -Path $Finding.MethodArgument -Value $Finding.RecommendedValue

Out-IniFile -InputObject $Data -FilePath $TempFileName -Encoding Unicode

&$BinarySecedit /import /cfg $TempFileName /overwrite /areas $Area /db $TempDbFileName /quiet | Out-Null

[...]

&$BinarySecedit /configure /db $TempDbFileName /overwrite /areas SECURITYPOLICY /quiet | Out-Null
```

**As I understand this section of code:**

1. The entire local security configuration is exported to a temporary INF file, limited to the area specified by `$Area`.
2. Within the INF file, one configuration value, the one corresponding to the current loop position of the CSV file, is updated.
3. The entire local security configuration is imported to a temporary security database using the temporary INF file, limited to the area specified by `$Area`.
4. The temporary security database is merged into the system security database.

**Now to my question:**

Why is it necessary to execute both the `/import` command and the `/configure` command? Wouldn't the end result be identical if only the `/configure` command was executed, like this:

```ps
[...]

&$BinarySecedit /export /cfg $TempFileName /areas $Area | Out-Null

$Data = Get-IniContent $TempFileName

Set-HashtableValueDeep -Table $Data -Path $Finding.MethodArgument -Value $Finding.RecommendedValue

Out-IniFile -InputObject $Data -FilePath $TempFileName -Encoding Unicode

&$BinarySecedit /configure /cfg $TempFileName /overwrite /areas $Area /db $TempDbFileName /quiet | Out-Null
```

> **URL:** https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/secedit-configure
> **Parameter:** /db
> **Description:** Required. Specifies the path and file name of the database containing the stored configuration. If the file name specifies a database that hasn't had a security template (as represented by the configuration file) associated with it, the /cfg <configuration file name> option must also be specified.

Thanks for your help!

**Comment by 0x6d69636b** [comment]
Hi Lukas

Thank you for your questions and your argument makes sense to me. I'll run some tests, but I think you're right, we can take this direct step.

Best, Mick

**Comment by 0x6d69636b** [comment]
I've done some tests and it looks good, I'm going to simplify the code

**Comment by lonkey** [comment]
I just want to say a big thank you for your outstanding work and for taking the time to review and incorporate my suggestion!

**Comment by 0x6d69636b** [comment]
You're welcome! 😻 By the way, what is the name of your project?

**Comment by lonkey** [comment]
A Python module that is able to fully parse GPO exports to convert them into configurable Ansbile roles. Unfortunately, it is closed-source as it is job-related.

**Comment by lonkey** [comment]
Thank you and I wish you the same. I will advise my employer to publish it publicly on GitHub in the future. After all, we ourselves would also benefit from a broader community-driven development.
