### ISSUE TITLE
Another Source for GPO's

### ISSUE THREAD

**Issue by beerisgood** [0x6d69636b/windows_hardening#28]
https://public.cyber.mil/stigs/gpo/

What did you think?

**Comment by 0x6d69636b** [comment]
I took a look at the Windows 10 policy, it looks doable. Presumably many settings can be taken directly from MSFT/CIS lists, it just looks like a bit of legwork.

Did you find a list with ID's or other identifiers, as far as I have seen there are only policies and reports?

**Comment by beerisgood** [comment]
I have not looked at it myself yet.
Still working with your (great!) :D

**Comment by 0x6d69636b** [comment]
I added the following lists, and matched them with IDs from [STIG Viewer](https://www.stigviewer.com/stigs)

- DoD Microsoft Windows 10 STIG (Machine)
- DoD Microsoft Windows 10 STIG (User)
- DoD Windows Server 2019 Domain Controller STIG (Machine)
- DoD Windows Server 2019 Domain Controller STIG (User)
- DoD Windows Server 2019 Member Server STIG (Machine)
- DoD Windows Server 2019 Member Server STIG (User)
- DoD Windows Defender Antivirus STIG | 2009
- DoD Windows Firewall STIG
