### ISSUE TITLE
HardeningKitty on non-english Windows

### ISSUE THREAD

**Issue by mrsheepsheep** [0x6d69636b/windows_hardening#35]
First, great work ! HardeningKitty is such a cute little thing.

As you mentioned in the readme, HardeningKitty may not support languages other than english, due to the fact that Windows is not consistent in its output depending on the installed system language...

A "quick" fix for most hardening lists is to translate files into the desired language. This mostly concerns finding methods with a localized result, such as `accesschk` or `auditpol`.

**In terms of following new commits on these files, how would you translate the lists ?**

Second problem that may or may not be a big issue : `accesschk` only supports ANSI encoding. Any accentuated character such as `é` and `è` (widely used in French for example) is not output correctly. In this case, `é` becomes `ù` and `è` is not printed. Same for apostrophe `'` becoming `?`. Standard encoding issues...

![AccesschkANSI](https://user-images.githubusercontent.com/4931825/116977737-13758080-acc3-11eb-86ea-cc508a1b42a9.png)

As you can see, the `NT AUTHORITY\System` - which translates as `AUTORITE NT\Système` is output as `AUTORITE NT\Systme`.
While replaced characters can be (unsafely) replaced, missing characters cannot be recovered...

I was hoping there was a way to enforce encoding for the `accesschk` binary, but haven't found any working solution. [Microsoft seems to be aware of the encoding issue](https://social.technet.microsoft.com/Forums/en-US/f53e8656-0535-427c-9eaa-e5f97a7d3b23/accesschk-can-not-deal-with-nonlatin-filenames?forum=utilsuggestions), but no update since last year...

The issue on its own is not related to HardeningKitty, but it could be mitigated in the script, if anyone has an idea.

**Comment by 0x6d69636b** [comment]
Thank you for your feedback and this issue. I have "feared" to receive such an issue soon and am currently working on a SID translation for accessk. As soon as I am ready, I would be happy for a test on your system

**Comment by mrsheepsheep** [comment]
#36 should be more appropriate to follow the issue, thank you !
