### ISSUE TITLE
MSFT: two Bugs in the Windows Server 2019 Audit

### ISSUE THREAD

**Issue by lordfiSh** [0x6d69636b/windows_hardening#39]
Hi, 
I found two possible bugs in the [finding_list_msft_security_baseline_windows_server_2004_member_machine.csv](https://github.com/0x6d69636b/windows_hardening/blob/master/lists/finding_list_msft_security_baseline_windows_server_2004_member_machine.csv) (maybe others too) 

```
[$] ID 10994, Windows Game Recording and Broadcasting: Enables or disables Windows Game Recording and Broadcasting, Result=0, Recommended=1, Severity=Medium
```
[I think the Recommended should be 0 and not 1 (?)](https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.GameDVR::AllowGameDVR)

```
[$] ID 10653, Network Connections: Prohibit use of Internet Connection Sharing on your DNS domain network, Result=1, Recommended=RequireMutualAuthentication=1,RequireIntegrity=1, Severity=Medium
[+] ID 10654, Network Provider: Hardened UNC Paths (NETLOGON), Result=RequireMutualAuthentication=1, RequireIntegrity=1, Severity=Passed
```
Probably a typo in Check 10653, copied from 10654.  [Values are only 0 or 1 ](https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.NetworkConnections::NC_ShowSharedAccessUI)

**Comment by 0x6d69636b** [comment]
Thanks! You are right in both cases and I fixed the bugs in commit https://github.com/0x6d69636b/windows_hardening/commit/f80322204e6f10f3a316ff7877603e2db435196e.
