### ISSUE TITLE
Add policy to disable advertising ID without blocking user choice

### ISSUE THREAD

**Issue by ataumo** [0x6d69636b/windows_hardening#44]
Hello, 

I would like to add policy to disable advertising ID without blocking user choice though `DisableByGroupPolicy` (not `DisabledByGroupPolicy`) in `HKLM:\SOFTWARE\Policies\Microsoft\Windows\AdvertisingInfo,DisableByGroupPolicy`

So, like that :
```
1696,"Administrative Templates: System","User Profiles: Turn of the advertising ID (Force)",Registry,,HKLM:\SOFTWARE\Policies\Microsoft\Windows\AdvertisingInfo,DisabledByGroupPolicy,,,,0,1,=,Medium
1697,"Administrative Templates: System","User Profiles: Turn of the advertising ID",Registry,,HKLM:\SOFTWARE\Policies\Microsoft\Windows\AdvertisingInfo,DisableByGroupPolicy,,,,0,1,=,Medium
```

But we already have policy with 1697 ID. What name can we give to this policy ?

**Comment by 0x6d69636b** [comment]
Could you please provide me with more information? I checked the group policy settings and found only the switch to turn it on/off. What would be the benefit of your setting?

**Comment by ataumo** [comment]
Ok, I made a mistake. I thought it was possible to disable advertising ID with this value : `DisableByGroupPolicy = 0` because, I have this property : 

![advertisinginfo_policy](https://user-images.githubusercontent.com/34421892/122720693-14ad3d80-d270-11eb-89cf-0bdf81a085c6.png)

It was for give a default configuration to the user and let him the choice to disable this : (sorry, my computer is in French)

![conf_panel_adv](https://user-images.githubusercontent.com/34421892/122721900-728e5500-d271-11eb-9bc1-f670b833da8c.png)

But it does not work. So, what is the purpose of `DisableByGroupPolicy` policy ?

**Comment by Harvester57** [comment]
This looks like a typo imported from a third-party tool. Have you ever used on your system any software marketed for privacy-enhancing Windows 10 ?

**Comment by ataumo** [comment]
Hum.. No, only HailMary from HardeningKitty. But, is it possible because I often modify the csv file to apply some tests.

**Comment by 0x6d69636b** [comment]
It might be that the typo was in an earlier version of my checklist and HardeningKitty created the registry key in HailMary mode :-/
