### ISSUE TITLE
Why do you use CimInstance instead of Regisrty for DeviceGuard policies ?

### ISSUE THREAD

**Issue by ataumo** [0x6d69636b/windows_hardening#45]
To enable DeviceGuard policy :

```
1614,"Administrative Templates: System","Device Guard: Virtualization Based Security Status",CimInstance,,,,Win32_DeviceGuard,root\Microsoft\Windows\DeviceGuard,VirtualizationBasedSecurityStatus,"Not available",2,=,Medium
```

Why do you use `CimInstance` instead of `Regisrty` like :

```
1614,"Administrative Templates: System","Device Guard: Virtualization Based Security Status",Registy,,HKLM:\Software\Policies\Microsoft\Windows\DeviceGuard,EnableVirtualizationBasedSecurity,,,,0,1,=,Medium
```

Also, `CimInstance` is not implemented in HailMary Mode. So, if your choice is justified to keep `CimInstance`, I can implement it.

**Comment by 0x6d69636b** [comment]
I use _CimInstance_ to double check if the setting is active or not. At the first versions of Windows 10 it was required to install VBS. If this was not installed, Device Guard was not active, even if all registry settings were correct. However, Device Guard should be configured over group policies. I use _CimInstance_ only for due diligence, but we do not need to implement a haily mary module.

**Comment by ataumo** [comment]
Ok, so, Device Guard configuration must be handmade :( ?

**Comment by 0x6d69636b** [comment]
Yes and No... The basics are covered here: https://github.com/0x6d69636b/windows_hardening/blob/master/windows_10_hardening.md#device-guard Afterwards you have to implement an application control policy, which has to be deployed to your systems, for example: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/deploy-windows-defender-application-control-policies-using-group-policy and how to plan a policy: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/plan-windows-defender-application-control-management

However, the creation of such a policy should be done individually, so it is not part of HardeningKitty. Above all, the impact on stability and running applications should not be underestimated. Not that suddenly important applications are blocked.
