### ISSUE TITLE
Path is too long failure in Starting Category Account Policies

### ISSUE THREAD

**Issue by MarkSe99** [0x6d69636b/windows_hardening#58]
Path is too long (expected a branch but arrived at a leaf before the end of the path)
At C:\GitHub\windows_hardening-master\Invoke-HardeningKitty.ps1:342 char:17
+ ...             throw "Path is too long (expected a branch but arrived at ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Path is too lon...nd of the path):String) [], RuntimeException
    + FullyQualifiedErrorId : Path is too long (expected a branch but arrived at a leaf before the end of the path)

Any ideas why you would see this?

**Comment by 0x6d69636b** [comment]
Can you give me more details, how was HardeningKitty run (mode, which file), on which check did the error occur, what operating system, language other than English?

**Comment by MarkSe99** [comment]
Apologies, this is on an English Win10 Enterprise 1809, running PoSH as Admin.

I ran 
Invoke-HardeningKitty -Mode Audit -Log -Report -ReportFile C:\temp\Hardening1.log

[*] 27/07/2021 13:55:38 - Starting Category Account Policies
Path is too long (expected a branch but arrived at a leaf before the end of the path)
At C:\github\windows_hardening-master\Invoke-HardeningKitty.ps1:342 char:17
+ ...             throw "Path is too long (expected a branch but arrived at ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Path is too lon...nd of the path):String) [], RuntimeException
    + FullyQualifiedErrorId : Path is too long (expected a branch but arrived at a leaf before the end of the path)

Log just shows this

[*] 27/07/2021 13:55:28 - Starting HardeningKitty
[*] 27/07/2021 13:55:28 - Getting machine information
[*] Hostname: XXXXX
[*] Domain: XXXX.com
[*] Domain role: MemberWorkstation
[*] Install date: 05/15/2020 09:16:59
[*] Last Boot Time: 07/19/2021 10:04:09
[*] Uptime: 8.03:51:18.8936104
[*] Windows: Windows 10 Enterprise
[*] Windows edition: Enterprise
[*] Windows version: 1909
[*] Windows build: 18362.1.amd64fre.19h1_release.190318-1202
[*] 27/07/2021 13:55:33 - Getting user information
[*] Username: USER
[*] Is Admin: True
[*] 27/07/2021 13:55:33 - Starting Category Features
ID 1000, SMBv1 Support, Result=Disabled, Severity=Passed
[*] 27/07/2021 13:55:38 - Starting Category Account Policies


From the hardening1.log I just see;
"ID","Name","Severity","Result","Recommended"
"1000","SMBv1 Support","Passed","Disabled"

**Comment by MarkSe99** [comment]
Sorry 1909 not 18, that is a typo

**Comment by 0x6d69636b** [comment]
Thank you for this information. The error message is part of the function `Get-HashtableValueDeep` which is used to go trough a secedit output. My guess is something went wrong with the secedit command, or the export files is not available. 

Could you please run the following commands and see if that works?

```powershell
$BinarySecedit = "C:\Windows\System32\secedit.exe"
$TempFileName = [System.IO.Path]::GetTempFileName()
$Area = "SECURITYPOLICY"
&$BinarySecedit /export /cfg $TempFileName /areas $Area 
```
The $TempFileName should contains values like this:
```
[System Access]
MinimumPasswordAge = 1
MaximumPasswordAge = 60
MinimumPasswordLength = 14
PasswordComplexity = 1
PasswordHistorySize = 24
LockoutBadCount = 10
ResetLockoutCount = 30
LockoutDuration = 30
...
```

**Comment by MarkSe99** [comment]
Thsis ran fine, I wonder if it errors out, as i get a lot of 
Warning 5: Access is denied.
 	Error setting security on machine\software\classes.

**Comment by 0x6d69636b** [comment]
Could you please send/upload the ini file from the commands? Then can I use them to debug
