### ISSUE TITLE
Getting Too many errors on clean install W10 21h1

### ISSUE THREAD

**Issue by mongeme** [0x6d69636b/windows_hardening#59]
Hello! 
I'm trying to apply hardening on new clean install Windows, but I'm getting a lot of errors in Account Policies.

[!] ID 1.1.1, Length of password history maintained, None, Failed to set account policy
[!] ID 1.1.5, System Access\PasswordComplexity, 0, Failed to import security policy into temporary database
[!] ID 1.1.6, System Access\ClearTextPassword, 0, Failed to import security policy into temporary database
[!] ID 1.2.2, Account lockout threshold, Never, Failed to set account policy
[!] ID 2.2.2, SeNetworkLogonRight, BUILTIN\Remote Desktop Users;BUILTIN\Administrators, Failed to configure system user right assignment
[!] ID 2.2.4, SeIncreaseQuotaPrivilege, BUILTIN\Administrators;NT AUTHORITY\NETWORK SERVICE;NT AUTHORITY\LOCAL SERVICE, Failed to configure system user right assignment
[!] ID 2.2.4, SeIncreaseQuotaPrivilege, BUILTIN\Administrators;NT AUTHORITY\NETWORK SERVICE;NT AUTHORITY\LOCAL SERVICE, Failed to configure system user right assignment
.......

Also in Category Advanced Audit Policy Configuration.
[!] ID 17.1.1, Credential Validation, Success and Failure, Failed to set audit policy
Erro 0x00000522:
The client does not have the necessary privilege.

[!] ID 17.2.1, Application Group Management, Success and Failure, Failed to set audit policy
Erro 0x00000522:
The client does not have the necessary privilege.

[!] ID 17.2.2, Security Group Management, Success, Failed to set audit policy
Erro 0x00000522:
The client does not have the necessary privilege. 

....

Funny that patched old installations are ok.

**Comment by 0x6d69636b** [comment]
I have to look into that... Which finding list did you use (CIS?)?

**Comment by mongeme** [comment]
My original was finding_list_cis_microsoft_windows_10_enterprise_1909_machine, then I tried a more recent finding_list_cis_microsoft_windows_10_enterprise_20h2_machine and finding_list_0x6d69636b_machine. I think MS sec patches changed permission on something.

**Comment by 0x6d69636b** [comment]
Sadly, I cannot reproduce that. I downloaded a Windows 10 ISO from Microsoft, setup a new VM and installed all updates. I only got one error "_[!] ID 2.2.14.2, SeCreateSymbolicLinkPrivilege, NT VIRTUAL MACHINE\Virtual Machines;BUILTIN\Administrators, Failed to configure system user right assignment_". I got this error because the _NT VIRTUAL MACHINE\Virtual Machines_ group does not exist on the system.

Is your system language English or do you use another language? 

![image](https://user-images.githubusercontent.com/13913706/127351681-886eb0a4-b4d7-45b1-91dc-e96c5ed7a56f.png)

**Comment by mongeme** [comment]
Following your question, I tried on US Windows, and it worked. The ones
that are working are because they were initially US, and the PT-BR language
pack was installed.



Is there a way to have Hardening kitty compatible? This will probably be my
homework.


Thank You Michael.

**Comment by 0x6d69636b** [comment]
There is always way :-) As a workaround you could replace the RecommendedValue values with your chosen language, Microsoft uses for user and group names the installed language and therefore HardeningKitty fails (if not English). So, when you replace _Administrator_ with the correct name (and the same for all groups like _Remote Desktop Users_), then it should work. The same applies for the audit policy, you can replace _Success_ and _Failure_ with your language and it should work.

The proper (and longer) way would be to create a full translation of the finding lists in Portuguese, see the translation issue: https://github.com/0x6d69636b/windows_hardening/issues/50
