### ISSUE TITLE
HailMary Mode in German?

### ISSUE THREAD

**Issue by Rxcmoon** [0x6d69636b/windows_hardening#61]
Hello good day,
Quick question before I test and maybe zer­schie­ßen my System :)

"Invoke-HardeningKitty -Mode HailMary -Log -Report -FileFindingList .\lists\finding_list_0x6d69636b_machine.csv"
Will that work for a German Windows?

Or as a workaround would it work to install Windows in English and change the language later after HailMary Mode?

Thank you for your time.

**Comment by 0x6d69636b** [comment]
The language setting affects "Advanced Audit Policy Configuration" and "User Rights Assignment", all other modules should not be affected. In the worst case, the settings simply remain in the default settings, the system should not break. ;-)

I believe installing the system in English and adding the German language package afterwards should work.

Either way, let me know if and how it worked out

**Comment by Rxcmoon** [comment]
Thanks you for the informations. Unfortunately it did not work. 
Got a lot of error messages every time I opened the GPO, all related to Advanced Audit Policy Configuration not found.
I deleted the lines Advanced Audit Policy Configuration and User Rights Assignment and did it via the GPO.

**Comment by 0x6d69636b** [comment]
Thanks for the update. Did you use version 0.6.1-1624286989 (commit https://github.com/0x6d69636b/windows_hardening/commit/0b913eec70021c5398b749bc36a742afe59b6d6a) which included a update for User Rights Assignment translation?
