### ISSUE TITLE
How can I use Invoke-HardeningKitty

### ISSUE THREAD

**Issue by celphogeek** [0x6d69636b/windows_hardening#62]
Hi,

I'm trying to use this hardening script, but appears this message 
![image](https://user-images.githubusercontent.com/29079236/128581451-5004c6b6-e8bd-4d03-bf5c-f608bb7cc117.png)

I try to see in the issues section but no information about this was found, what am I doing wrong?

Could someone explain please the steps 

Here's the folder content of this script downloaded and extracted 
![image](https://user-images.githubusercontent.com/29079236/128581495-a48eb3e1-9d35-49d7-937f-f8b31f8b156c.png)

**Comment by 0x6d69636b** [comment]
Try to import the file using a relative path: `Import-Module .\Invoke-HardeningKitty.ps1`, then it should work.

![start_hardeningkitty](https://user-images.githubusercontent.com/13913706/128589029-99acba12-313e-4664-af8f-6d5adb659195.png)

**Comment by celphogeek** [comment]
Yes it works, thanks 
![image](https://user-images.githubusercontent.com/29079236/128603365-b805f4b6-ca9c-4943-ab12-b1913994e2d3.png)
