### ISSUE TITLE
The variable cannot be validated because the value

### ISSUE THREAD

**Issue by aermak** [0x6d69636b/windows_hardening#77]
`The variable cannot be validated because the value
C:\Users\#######\Downloads\lists\finding_list_0x6d69636b_machine.csv is not a valid value for the FileFindingList
variable.
At C:\Test\Invoke-HardeningKitty.ps1:663 char:13
+             $FileFindingList = "$CurrentLication\lists\finding_list_0 ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ValidationMetadataException
    + FullyQualifiedErrorId : ValidateSetFailure

Import-Csv : Cannot validate argument on parameter 'Path'. The argument is null or empty. Provide an argument that is
not null or empty, and then try the command again.
At C:\Test\Invoke-HardeningKitty.ps1:666 char:41
+         $FindingList = Import-Csv -Path $FileFindingList -Delimiter " ...
+                                         ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Import-Csv], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.ImportCsvCommand`

**Comment by 0x6d69636b** [comment]
Sorry I can't reproduce the issue. Are you using the current version of HardeningKitty? Could you please verify if the finding list is complete and not corrupted in any way?

The SHA1 hash of the list ist:
`a4906a8a7626ffc6083a75d14f5b10d21eee475d  lists/finding_list_0x6d69636b_machine.csv`

**Comment by aermak** [comment]
That worked, deleted everything, downloaded latest version and all works fine now, thanks!

**Comment by jacobyoby** [comment]
I had this issue also. Failing to copy the "lists" folder to the directory where the script is running will cause this.

**Comment by 0x6d69636b** [comment]
I wrote a check for that: https://github.com/0x6d69636b/windows_hardening/commit/f3b54e59e0aa3374369a101f81a724c995f04aa4
