### ISSUE TITLE
ID 1740 has a blank recommended setting.

### ISSUE THREAD

**Issue by c3rberus** [0x6d69636b/windows_hardening#8]
When running the script in audit, one of the outputs is:

**[$] ID 1740, Search: Allow Cloud Search, Result=0, Recommended=, Severity=Medium**

The recommended value is blank, this should be 0 so that it is disabled.

Ref: https://www.tenforums.com/tutorials/88731-enable-disable-show-cloud-content-search-results-windows-10-a.html

**Comment by 0x6d69636b** [comment]
Thank you, I fixed it in commit [4877264](https://github.com/0x6d69636b/windows_hardening/commit/48772642ce9675ab46cafc738773a819dd362643).
