### ISSUE TITLE
Recommended value not displayed correctly

### ISSUE THREAD

**Issue by rainer-helbing** [0x6d69636b/windows_hardening#80]
I tried to run the CIS findings list for Windows Server 2019 and got wrong values for _recommended_ in the log and in the report.  
I reduced the findings list to 4 lines to reproduce the error.

### findings fist
```
ID,Category,Name,Method,MethodArgument,RegistryPath,RegistryItem,ClassName,Namespace,Property,DefaultValue,RecommendedValue,Operator,Severity
2.2.19,"User Rights Assignment","Debug programs",accesschk,SeDebugPrivilege,,,,,,BUILTIN\Administrators,BUILTIN\Administrators,=,Medium
2.2.20,"User Rights Assignment","Deny access to this computer from the network (DC)",accesschk,SeDenyNetworkLogonRight,,,,,,"BUILTIN\Guests","BUILTIN\Guests",=,Medium
2.2.21,"User Rights Assignment","Deny access to this computer from the network (Member)",accesschk,SeDenyNetworkLogonRight,,,,,,"BUILTIN\Guests","BUILTIN\Guests",=,Medium
```

### error
In the report and the log the value for recommended is `BUILTIN\Administrators` instead of `BUILTIN\Guests`. The actual value for 2.2.20 / 2.2.21 is empty (no groups are denied).

![KittyErrors](https://user-images.githubusercontent.com/39090978/158859427-62cf773b-1a08-470c-b55c-d2913aedab21.png)

Report output:
```
"ID","Name","Severity","Result","Recommended"
"2.2.19","Debug programs","Passed","BUILTIN\Administrators"
"2.2.20","Deny access to this computer from the network (DC)","Medium","","BUILTIN\Administrators"
"2.2.21","Deny access to this computer from the network (Member)","Medium","","BUILTIN\Administrators"
```

HailMary mode seems not to be affected from this error

**Comment by 0x6d69636b** [comment]
Thank you for spotting this bug, the very helpful issue description, and test file. The bug is only triggered when the result was empty. Could you please update HardeningKitty and test it again - I pushed a fix to the repo (https://github.com/0x6d69636b/windows_hardening/commit/96717bd8c24cd829cb37af6b61b02ccd79c285fb)

**Comment by rainer-helbing** [comment]
The fix displays the expected results (log and report).

Thanks a lot :-)
