### ISSUE TITLE
Possible duplicates in baselines

### ISSUE THREAD

**Issue by furmelade** [0x6d69636b/windows_hardening#83]
When checking some baselines, i have encounted some possible duplicates, i.e.
File: `finding_list_cis_microsoft_windows_10_enterprise_1809_machine.csv`

`9.2.3,"Windows Firewall","Outbound Connections (Private Profile, Policy)",Registry,,HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile,DefaultOutboundAction,,,,0,0,=,Medium`
And
`9.3.3,"Windows Firewall","Outbound Connections (Private Profile, Policy)",Registry,,HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile,DefaultOutboundAction,,,,0,0,=,Medium`

Both reference the Private Firewall profile, whereas the entry before references either the Public or the Private profile.

I found the same issue in following files:
`finding_list_cis_microsoft_windows_10_enterprise_1903_machine.csv
finding_list_cis_microsoft_windows_10_enterprise_1909_machine.csv
finding_list_cis_microsoft_windows_10_enterprise_2004_machine.csv
finding_list_cis_microsoft_windows_10_enterprise_20h2_machine.csv
finding_list_cis_microsoft_windows_10_enterprise_21h1_machine.csv
finding_list_cis_microsoft_windows_11_enterprise_21h2_machine.csv
finding_list_bsi_sisyphus_windows_10_nd_machine.csv
finding_list_bsi_sisyphus_windows_10_ne_machine.csv`

Furthermore i found a similar issue in File: `finding_list_bsi_sisyphus_windows_10_nd_machine.csv`
With a duplicate:
`64,"Administrative Templates: System","Group Policy: Do not apply during periodic background processing",Registry,,"HKLM:\Software\Policies\Microsoft\Windows\Group Policy\{35378EAC-683F-11D2-A89A-00C04FBBCFA2}",NoGPOListChanges,,,,0,0,=,Medium`
`65,"Administrative Templates: System","Group Policy: Do not apply during periodic background processing",Registry,,"HKLM:\Software\Policies\Microsoft\Windows\Group Policy\{35378EAC-683F-11D2-A89A-00C04FBBCFA2}",NoGPOListChanges,,,,0,0,=,Medium`

**Comment by 0x6d69636b** [comment]
Thank you, fixed with commit https://github.com/0x6d69636b/windows_hardening/commit/8aeb0d1d4cd5e0d2067029d35c7ada9d52031e53
