### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by asterictnl-lvdw** [0x6d69636b/windows_hardening#87]
Hello,

When I execute the script .\Invoke-Hardeningkitty.ps1 it does nothing. There is not console output and it just like the command completed without displaying output.

Is there something wrong with the script?

Let me know.

**Comment by 0x6d69636b** [comment]
HardeningKitty is a PowerShell module, this is the normal behaviour, you have to run it like this:
```
Import-Module .\Invoke-HardeningKitty.ps1
Invoke-HardeningKitty
```

The example documentation describes various functions:
https://github.com/0x6d69636b/windows_hardening#examples

**Comment by asterictnl-lvdw** [comment]
Hello,

The main problem is that I want to execute it like this:

`powershell -Command Import-Module C:\temp\hkitty\windows_hardening-master\Invoke-HardeningKitty.ps1 && powershell - Command `

I want to do this so I can execute an remote audit via SSH or PSExec when neccesary. I want to know if this is possible or that the script needs to be rewritten for this purpose?

**Comment by asterictnl-lvdw** [comment]
PS: I might have found the issue to mitigate this:

In order to execute a remote audit you can do the following:
1) Create another .ps1 file and add these two lines:

`Import-Module .\Invoke-HardeningKitty.ps1
Invoke-HardeningKitty`

This way you can execute:

`powershell -Command {path}\Execute-HardeningKitty.ps1`

So you have an One-Liner to execute the command. 

Of course this command could be improved for example by adding the respective possible arguments .

**Comment by 0x6d69636b** [comment]
I see, you could achieve this in one command like so:
```powershell
powershell.exe -Command "Import-Module C:\temp\hkitty\windows_hardening-master\Invoke-HardeningKitty.ps1; Invoke-HardeningKitty -FileFindingList C:\temp\hkitty\windows_hardening-master\lists\finding_list_0x6d69636b_machine.csv"
```
