### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by TechZerkerGit** [0x6d69636b/windows_hardening#9]
I'm not sure what I'm missing, maybe it's simple, but all downloaded and AccessChk variable set, attempting to run in Admin Powershell, I get:

```
ParserError: C:\Utilities\Invoke-HardeningKitty.ps1:138
Line |
 138 |  … etails px-3 px-md-4 px-lg-5 flex-wrap flex-md-nowrap" role="banner" >
     |                                                                         ~
     | Missing file specification after redirection operator.
```

**Comment by 0x6d69636b** [comment]
Interesting, can you tell me how you started Invoke-HardeningKitty, with which parameters?

**Comment by 0x6d69636b** [comment]
I have made several updates. I am closing the issue, please test again with the latest version and if the problem still exists, you can open a new issue.
