### ISSUE TITLE
Windows Firewall rules that are pushed via GPO are not reported

### ISSUE THREAD

**Issue by exceedio** [0x6d69636b/windows_hardening#90]
Line 1254 of Invoke-HardeningKitty.ps1 uses Get-NetFirewallRule with the -DisplayName parameter to query firewall rules on the local system. I have found that rules that were pushed by GPO are not returned by Get-NetFirewallRule without adding **-PolicyStore ActiveStore** as a parameter.

Here is a screenshot of the firewall rules and script results on Windows 10 Ent 21H2:

![image](https://user-images.githubusercontent.com/587299/167138781-21ec24a4-9f97-45f0-9da1-056d28cd3d87.png)

Here is a screenshot of running Get-NetFirewallRule on the same system with and without the -PolicyStore parameter:

![image](https://user-images.githubusercontent.com/587299/167139792-9dbf4bc6-bfc0-49f7-b222-5ca410dceeda.png)

From my limited testing it looks like adding **-PolicyStore ActiveStore** adds to the count of firewall rules returned so there might be no harm in adding it. The count of **Get-NetFirewallRule -PolicyStore ActiveStore** on my machine is exactly five more than the count of **Get-NetFirewallRule** which accounts for the five rules I pushed by GPO.

![image](https://user-images.githubusercontent.com/587299/167141160-64417d40-cb18-476c-bcd4-4e2e935993da.png)

This could also be me just completely missing something after staring at things for too long!

**Comment by 0x6d69636b** [comment]
Nice catch! I did not know that there are different stores. The *ActiveStore* combines all rules (GPO, manually added). I added the rules over HardeningKitty on my systems, and they land in the *PersistentStore* so my tests were always successful. Microsoft has documented it [here](https://docs.microsoft.com/en-us/powershell/module/netsecurity/set-netfirewallsetting?view=windowsserver2022-ps&viewFallbackFrom=win10-ps). I added the -PolicyStore switch to the script in commit https://github.com/0x6d69636b/windows_hardening/commit/b30942113b5d65f46d1c178b274b5ed2f2c11bd7.
