### ISSUE TITLE
TLS PKCS ServerMinKeyBitLength/ClientMinKeyBitLength

### ISSUE THREAD

**Issue by pmatula** [0x6d69636b/windows_hardening#96]
Both lists `finding_list_microsoft_windows_tls` and `finding_list_microsoft_windows_tls_future` contains: ID1051:  "PKCS (ServerMinKeyBitLength)". 

But in reality it checks the `ClientMinKeyBitLength` value name. There seems to be a mismatch. Regarding: https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings#keyexchangealgorithm---diffie-hellman-key-sizes only ClientMinKeyBitLength exists. 

I would therefore suggest changing the description (because the check itself seems correct).

**Comment by 0x6d69636b** [comment]
Absolutely, you are right. I'll fix that in a bit
